### ISSUE TITLE
Wayland and pulseaudio dependencies

### ISSUE THREAD

**Issue by Iliolou** [vkohaupt/vokoscreenNG#166]
I do not see why a screencast application should have such hardcoded dependencies.
They should be optional, like in the original version.

Many people still running happily with X and alsa or jack.

**Comment by vkohaupt** [comment]
Wayland:
In the next update, only the wayland-client library is required. This is currently only used to detect whether the desktop is running under wayland. If so, a dialog appears with the message that you should switch to an X11 desktop. 

Alsa:
About 4 years ago only 3% of users used a pure Alsa system. For a few users, months of work, no. And the disadvantages you deal with Alsa do not justify this work anyway.
When I got your email yesterday I started my KDE system without pulse audio. I saw no speakers and microphones, nothing. Then I started another screencast program that Alsa still supports. I played the recorded video with VLC and heard the sound in a Mickey Mouse voice. After closing VLC, this Mickey Mouse voice was always to be heard in an endless loop, so that I had to shut down my system.
And now I ask you, would you sacrifice your time for something like that?

**Comment by embeddedt** [comment]
On Ubuntu 18.04, I had to apply the following patch to waylandRoutines/QvkWaylandRoutines.cpp to compile successfully:

```diff
-#include "wayland/wayland-client.h"
+#include "wayland-client.h"
```

It seems that Ubuntu stores `wayland-client.h` in `/usr/include` directly.

**Comment by Iliolou** [comment]
First I would like to thank you for your effort. Your app is really nice and useful,

And imho the killer feature that brought me here was the mouse click animation.
Btw, it would be nice to support svgs through QSvgRenderer instead of the QLabel widget you use right now.
In this way we could use pulse effects such as https://dribbble.com/shots/3099510-iOS-Pulse and others.

About the audio, what I had in mind was modular output plugins. out_alsa.so, out_pa.so and out_jack.so., but I guess you are right about the users case.

I am doing music production and only use jack. However both pa and jack are on top of alsa.
Alsa is pretty stable, not user-friendly particularly with bluetooth (which was pulseaudio's trojan horse to win the game), but stable.

It's a bit off topic, but that is exactly that worries me about the evolution of the linux desktop. It's not about options anymore.
Hardcoded dependencies backed up by big names like Red Hat and Canonical. It's so hard to find nowadays a distro without pulseaudio and systemd.
I hope this guy will do us a favor, stop writing software for linux and move to Windows.

Anyway thanks again.

**Comment by vkohaupt** [comment]
@embeddedt

https://github.com/vkohaupt/vokoscreenNG/commit/aa72c64c90772fb0581950de52a3838cef57bfbd

Thanks for the hint.
