### ISSUE TITLE
Audio and snap

### ISSUE THREAD

**Issue by vkohaupt** [vkohaupt/vokoscreenNG#55]
Many users have problems with audio and snap.
I have tested with Ubuntu 18.04 and 19.10 and always have pulseaudio!!!!
My question. How the hell do you manage to have no pulse audio using "sudo snap install vokoscreen-ng"?

**Comment by jrandiny** [comment]
If this is regarding the audio recording feature, I think it's because `audio-record` interface is not automatically connected by default (https://snapcraft.io/docs/audio-record-interface). If I'm not mistaken, there is a request process for enabling auto connection for specific snap (https://snapcraft.io/docs/permission-requests).

For example here is the `audio-record` request for the chromium snap :
https://forum.snapcraft.io/t/auto-connecting-the-audio-record-interface-for-the-chromium-snap/16105

**Comment by vkohaupt** [comment]
I have now solved it like this.
![test-2](https://user-images.githubusercontent.com/3152567/77227134-3eb01580-6b7e-11ea-8257-d247fac3b122.png)
